# Generated by Django 4.2.6 on 2023-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location_alter_user_phone_number_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='peofile_id',
            new_name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
