# Generated by Django 4.2.6 on 2023-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_peofile_id_profile_profile_id_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default='', max_length=16),
        ),
    ]
